### ISSUE TITLE
Fix storybook

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1136]
Broke here: https://github.com/ji-devs/ji-cloud/actions/runs/994506799

**Comment by MendyBerger** [comment]
Fixed in b205c3161cc7a28c71e1b7fc608b704c2d83af55

**Comment by dakom** [comment]
Re-opening, that commit didn't fix it: https://github.com/ji-devs/ji-cloud/actions/runs/1004002587
