### ISSUE TITLE
Heroes: Shai Reshef by Chaykee - video link needs to be updated

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2357]
Video on page 3 is unavailable. Please update with new link.

![Screen Shot 2022-02-01 at 2 33 21 PM](https://user-images.githubusercontent.com/78186896/151969624-39969adc-4f72-44f7-a5f3-55b95612a73e.png)

**Jigzi:**
https://jigzi.org/admin/curation/dc53b19e-69d2-11ec-a181-636f3cf51468

**JiTap:**
https://jitap.net/activities/g5p2/play/

**Comment by corinnewo** [comment]
@ChaykeeMor Do you know what the updated video link should be?

**Comment by ChaykeeMor** [comment]
I don't remember what was there but put this:
https://www.youtube.com/watch?v=HuuxwJddmks


*Home Learning Resource Page
<https://www.jewishinteractive.org/kids-learning-at-home/?utm_campaign=Corona%20Virus%202020&utm_medium=email&_hsenc=p2ANqtz-_SraQgS9WX1G3lE1aYsRKe0HV2O6-sPCFDj0qt4uVJmUB8urgTFCFHn1lg79dfBndxUACJk6phIUyZtSwy5XufobunMMNPv9ldekS65SLgRnM3Y1g&_hsmi=84346719&utm_source=hs_email&utm_content=84346719&hsCtaTracking=246ab963-de67-4298-b856-ff8aceff5472%7C622416ad-a3d4-4483-9c4b-395eb3f36104>*
*www.jewishinteractive.org <https://www.jewishinteractive.org/>*
*www.jitap.net <https://www.jitap.net/>*

<https://twitter.com/ChanaKanzen>
<https://www.facebook.com/JewishInteractive>
<http://www.linkedin.com/company/jewish-interactive>
<http://www.youtube.com/user/JewishInteractive>
<http://jewishinteractive.net/site/blog-2/feed/>

**Comment by corinnewo** [comment]
@chayaml I had corrected this link in Jigzi, and now with David reimporting, it is broken again. I see that in Ji Tap, the video link is still broken. PLease fix the Ji Tap link, and I will make sure that the Jigzi one is good.
Ji Tap: https://jitap.net/activities/g5p2/play/ (screen 3)

**Comment by ChaykeeMor** [comment]
I fixed the link in JiTap. It should work with the new link.

**Comment by corinnewo** [comment]
Great - Thanks!

**Comment by corinnewo** [comment]
@ChaykeeMor The link in Ji Tap is still broken. Please check https://jitap.net/activities/g5p2/play/ 
Thanks

**Comment by ChaykeeMor** [comment]
I don't know how to fix this. It is not broken. This is the link: https://www.youtube.com/watch?v=HuuxwJddmks and it works on my iPad and I updated it on JiTap... What else can I do?

**Comment by corinnewo** [comment]
Very strange - it is now working on Ji Tap. It was definitely broken 5 days ago!
Thanks - I have to fix on Jigzi anyway, but that's great if Ji Tap is now good.

**Comment by corinnewo** [comment]
@MendyBerger Please look at this - the video is still not working.
Ji Tap: g5p2
Game ID: 6148

**Comment by corinnewo** [comment]
Finally changed the video!
