### ISSUE TITLE
Memory Game: buttons cropped out of canvas with full screen

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2427]
I'm on full screen and "remove image/ delete pair" is cropped out on the right. I'm not sure if this has already been addressed - maybe #1797 - but I'm opening it here.

![Screen Shot 2022-02-17 at 4 25 04 PM](https://user-images.githubusercontent.com/78186896/154501889-6872668a-6407-4419-97f9-19a4e45693c9.png)

**Comment by corinnewo** [comment]
@MendyBerger Should this not be taken care of with David's fix of repositioning the menus if they go out of the area?

**Comment by MendyBerger** [comment]
I would think it was fixed, but apparently that's not the case, will have to look into this

**Comment by corinnewo** [comment]
@MendyBerger This is still an issue! Menu items are cut off instead moving to be on the canvas.

**Comment by corinnewo** [comment]
Closing in favor of https://github.com/ji-devs/ji-cloud/issues/4095
