### ISSUE TITLE
Find the answer - first comments

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2947]
- [x] Use cases - Scene and text rollovers are too large - Corinne will fix
- [x] If there is only sound, and there is a question box, then it should be empty when the sound plays. I had a question from the previous question on screen, even though I was asking about something else.
- [x] When you preview, the last question has not sound effect
- [x] The cursor should not change over the correct answer!
- [x] Sometimes, the CONTINUE button on the interaction does not work - clicking it does not take you anywhere
- [x] I cannot publish - the button does not get enabled. Has a problem with the cover, not sure why! But I cannot get past it to publish.
- [x] IF there is audio for the instruction, then play the audio first and then the audio of the first question - probably need a little pause too. At the moment they are playing simultaneously.
- [x] If you click on a non-answer, should get a negative sound effect

**Comment by johnnynotsolucky** [comment]
@corinnewo:

> If you click on a non-answer, should get a negative sound effect

Once we have the advanced config, there could be a negative recording for the wrong answer - should we play a negative effect if there is no audio? 

Also, will clicking anywhere other than an answer trace be a wrong answer?

> Sometimes, the CONTINUE button on the interaction does not work - clicking it does not take you anywhere

This hasn't been implemented yet. I'll implement as part of this issue.

> IF there is audio for the instruction, then play the audio first and then the audio of the first question - probably need a little pause too. At the moment they are playing simultaneously.

Yip, we have an instructions player component which handles the instructions text and audio. I briefly had a look into it, and think it might be a bit of work to fix this issue. What I'd like to do is have the instructions play first, and once completed, start the activity. However from what I can tell, that ability is not implemented, so I'll need to add that to the component to fix this.

**Comment by corinnewo** [comment]
@johnnynotsolucky added in my responses in CAPS.

**Comment by johnnynotsolucky** [comment]
@corinnewo I fixed an issue with is_complete in #2959, but it wasn't the same case that you reported. It was when a teacher adds a question without text and uploads audio for the question instead, which meant that the title doesn't get a value, it just defaults to "Question _n_" based on the position of it in the list of questions.

**Comment by corinnewo** [comment]
@johnnynotsolucky those hover states of the use cases are still huge - the image I replaced is still not showing. Please can you look into it? thanks

**Comment by johnnynotsolucky** [comment]
@corinnewo there is still an issue with the dropbox sync, so no media is being updated on the app at the moment.
