### ISSUE TITLE
Double X visible when you play a course from the play button on top of course

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3528]
When you play an individual game within a course, the game opens up in the regular player - full screen.

When you play the course from the PLAY button at the top of the screen, the course remains open underneath, and the JIG opens up on top. As a result, there are 2 CLOSE buttons visible. Can we hide the X on the course when a JIG is playing?

![double-x-course play](https://user-images.githubusercontent.com/16290361/210797768-9bb46fc0-1566-49f2-9755-fac9e02752dd.JPG)

**Comment by MendyBerger** [comment]
Resolved a long time ago

**Comment by corinnewo** [comment]
This is still happening! Please hide the X of the course on the top right when the JIG is playing.
![Uploading image.png…]()

**Comment by MendyBerger** [comment]
@corinnewo can you re-upload the image please?

**Comment by corinnewo** [comment]
I went into sandbox to take a screen grab again, and it has been fixed! THanks. Closing!
