### ISSUE TITLE
In course creator, panel on left - "Play JIG" on Kebab menu crashes

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3683]
When you try and play a JIG from the kebab menu on the left, there is a crash:

![image](https://user-images.githubusercontent.com/16290361/218981802-f26629d4-d8d8-4f5f-9ce3-db3ffd000c31.png)

Also, empty kebab menu on an inserted item - can't delete it:
![image](https://user-images.githubusercontent.com/16290361/218982111-fe90dfdd-a198-4aed-afc5-ad3fa39a5661.png)

ALSO the info causes a crash.

**Comment by corinnewo** [comment]
@MendyBerger If INFO and PLAY JIG are crashing, should we not just hide them from the kebab menu until they are fixed? The crash is happening on the live version too!! Move up and down are working, and we can leave them in.

**Comment by MendyBerger** [comment]
Resolved

**Comment by corinnewo** [comment]
@MendyBerger thanks for hiding the **Play** item on the kebab menu. But you did not hide the **JIG Info** item, and that is also still crashing! Please hide **Info** too! Thanks!

**Comment by MendyBerger** [comment]
Resolved
