### ISSUE TITLE
Embedded player does not have the fullscreen icon (on desktop)

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3716]
I tested embedding the new player with the full-screen icon here: https://www.jewishinteractive.org/test-embed/

It does not show the fullscreen icon, even though I am on a desktop.  You need to explicitly enable fullscreen.

Please add the enabling of fullscreen to the embed code.

![image](https://user-images.githubusercontent.com/16290361/221619770-6788cf56-8503-423a-a89d-f26899be1f78.png)

**Comment by MendyBerger** [comment]
Resolved.

For existing embedded jigs, either update with the new embed code, or just add `allow="autoplay; fullscreen"` to the iframe.
E.g.
```html
<iframe src="https://sandbox.jigzi.org/asset/play/jig/531595d8-6260-11ec-8f97-d79fa4eaf220?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=true&draft_or_live=live" width="960" height="540" allow="autoplay; fullscreen"></iframe>
```

**Comment by corinnewo** [comment]
@MendyBerger I am still not seeing the fullscreen icon in the embedded items - even with the new code. Please see https://www.jewishinteractive.org/test-embed/ - The first item is with the new embed code, and the second item is with the extra code added to the previous iframe code. (Which I know both are identical...). Neither is showing the icon.

**Comment by corinnewo** [comment]
Interesting - I tried taking out the autoplay, and left in allow="fullscreen" in the first item only, then suddenly both embedded sandbox items had the fullscreen icon!

**Comment by MendyBerger** [comment]
Me and @corinnewo decided that it's not worth spending additional time on this until we hear from users that they need it
