### ISSUE TITLE
QA Publish (Publish Full Two) - Correct text under animation placeholder

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#691]
[Zeplin sketch](https://app.zeplin.io/project/5f10b1dc713f249d469be791/screen/5fb6da2046e152a9017335ca) features text that reads as follows:

**Heading/Title:** Your JIG is on air now 
**Regular Text:** What would you like to do next? 

Current [Storybook screen](https://storybook.sandbox.jicloud.org/?path=/story/full-pages-publish--publish-full-two) features incorrect text.

Please correct text under animation text holder.

---

**Zeplin Sketch:**

![Publish_21_A_PublishFullTwo_JIGOnAir_Zeplin](https://user-images.githubusercontent.com/74170693/104878482-0ad28780-592a-11eb-921c-d64bd6abad62.png)

---

**Storybook Screen:**

![Publish_21_B_PublishFullTwo_JIGOnAir_SB](https://user-images.githubusercontent.com/74170693/104878483-0b6b1e00-592a-11eb-9e25-0d95d5422d1f.png)

**Comment by NaomiLea** [comment]
Fixed

**Comment by dani-ji** [comment]
@NaomiLea was this pushed? I still see the old version in SB

**Comment by dakom** [comment]
there are a lot of pending changes in the latest PR: https://github.com/ji-devs/ji-cloud/pull/735

(the PR currently has outstanding review issues that must be resolved before merging)

**Comment by NaomiLea** [comment]
Most of them comes from Rivkas files and Id like to go through them with her. Can we do a pull request and involve all those files?

**Comment by dakom** [comment]
That PR seems to involve all her files now - if I'm missing something let me know and we can jump on a call to sort it out

**Comment by NaomiLea** [comment]
fixed
