### ISSUE TITLE
Discrepancy in button

### ISSUE THREAD

**Issue by dani-ji** [ji-devs/ji-cloud#728]
Zeplin has a different shape button that says continue and has an arrow
![Screen Shot 2021-01-20 at 2 00 03 PM](https://user-images.githubusercontent.com/73904351/105222296-53579400-5b28-11eb-93f8-40a9bfa6ca0d.png)
![Screen Shot 2021-01-20 at 2 00 09 PM](https://user-images.githubusercontent.com/73904351/105222298-53579400-5b28-11eb-9d31-405900befbc1.png)

**Comment by NaomiLea** [comment]
Fixed

**Comment by dani-ji** [comment]
@NaomiLea not resolved on this page https://storybook.sandbox.jicloud.org/?path=/story/entry-user-login-pages--landing

**Comment by dakom** [comment]
duplicate of https://github.com/ji-devs/ji-cloud/issues/1323
